linters:
  enable-all: true
  disable:
    - execinquery    # Deprecated
    - exportloopref  # Deprecated
    - gomnd          # Deprecated
    - depguard
    - nolintlint
    - nlreturn
    - wrapcheck
    - ireturn
    - varnamelen

linters-settings:
  varnamelen:
    ignore-names:
      - tt
