linters:
  enable-all: true
  disable:
    - execinquery    # Deprecated
    - exportloopref  # Deprecated
    - gomnd          # Deprecated
    - depguard
    - nolintlint

linters-settings:
  varnamelen:
    ignore-names:
      - tt
