version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# https://goreleaser.com/customization/homebrew/
brews:
  - repository:
      owner: kazuki-iwanaga
      name: homebrew-tap
      token: "{{ .Env.PAT_HOMEBREW_TAP_REPO }}"
    homepage: "https://github.com/kazuki-iwanaga/pr2otel"
    description: "pr2otel is a tool to convert Pull Request to OpenTelemetry-compatible telemetry."
    license: "MIT"

# https://goreleaser.com/customization/docker/
# https://goreleaser.com/cookbooks/multi-platform-docker-images/
dockers:
  - image_templates:
      - "ghcr.io/kazuki-iwanaga/pr2otel:{{ .Tag }}-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/kazuki-iwanaga/pr2otel:{{ .Tag }}-arm64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    goarch: "arm64"
docker_manifests:
  - name_template: "ghcr.io/kazuki-iwanaga/pr2otel:{{ .Tag }}"
    image_templates:
      - "ghcr.io/kazuki-iwanaga/pr2otel:{{ .Tag }}-amd64"
      - "ghcr.io/kazuki-iwanaga/pr2otel:{{ .Tag }}-arm64"
