version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Tag }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc

# https://goreleaser.com/customization/homebrew/
brews:
  - repository:
      owner: kazuki-iwanaga
      name: homebrew-tap
      token: "{{ .Env.PAT_HOMEBREW_TAP_REPO }}"
    homepage: "https://github.com/kazuki-iwanaga/pr2trace"
    description: "A CLI tool to convert Pull Request to OpenTelemetry-compatible telemetry."
    license: "MIT"

# https://goreleaser.com/customization/docker/
# https://goreleaser.com/cookbooks/multi-platform-docker-images/
dockers:
  - image_templates:
      - "{{ .Env.TARGET_IMAGE_NAME }}:{{ .Tag }}-amd64"
      - "{{ .Env.TARGET_IMAGE_NAME }}:v{{ .Major }}-amd64"
      - "{{ .Env.TARGET_IMAGE_NAME }}:v{{ .Major }}.{{ .Minor }}-amd64"
      - "{{ .Env.TARGET_IMAGE_NAME }}:latest-amd64"
    use: buildx
    dockerfile: .goreleaser.dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
  - image_templates:
      - "{{ .Env.TARGET_IMAGE_NAME }}:{{ .Tag }}-arm64"
      - "{{ .Env.TARGET_IMAGE_NAME }}:v{{ .Major }}-arm64"
      - "{{ .Env.TARGET_IMAGE_NAME }}:v{{ .Major }}.{{ .Minor }}-arm64"
      - "{{ .Env.TARGET_IMAGE_NAME }}:latest-arm64"
    use: buildx
    dockerfile: .goreleaser.dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    goarch: "arm64"
docker_manifests:
  - name_template: "{{ .Env.TARGET_IMAGE_NAME }}:{{ .Tag }}"
    image_templates:
      - "{{ .Env.TARGET_IMAGE_NAME }}:{{ .Tag }}-amd64"
      - "{{ .Env.TARGET_IMAGE_NAME }}:{{ .Tag }}-arm64"
  - name_template: "{{ .Env.TARGET_IMAGE_NAME }}:v{{ .Major }}"
    image_templates:
      - "{{ .Env.TARGET_IMAGE_NAME }}:v{{ .Major }}-amd64"
      - "{{ .Env.TARGET_IMAGE_NAME }}:v{{ .Major }}-arm64"
  - name_template: "{{ .Env.TARGET_IMAGE_NAME }}:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "{{ .Env.TARGET_IMAGE_NAME }}:v{{ .Major }}.{{ .Minor }}-amd64"
      - "{{ .Env.TARGET_IMAGE_NAME }}:v{{ .Major }}.{{ .Minor }}-arm64"
  - name_template: "{{ .Env.TARGET_IMAGE_NAME }}:latest"
    image_templates:
      - "{{ .Env.TARGET_IMAGE_NAME }}:latest-amd64"
      - "{{ .Env.TARGET_IMAGE_NAME }}:latest-arm64"
