pre-commit:
  piped: true
  commands:
    1_gomodtidy:
      glob: "*.go"
      run: go mod tidy -diff
    2_golangcilint:
      glob: "*.go"
      run: golangci-lint run ./...
    3_gotest:
      glob: "*.go"
      run: go test -v ./...

pre-push:
  piped: true
  commands:
    1_gomodtidy:
      glob: "*.go"
      run: go mod tidy -diff
    2_golangcilint:
      glob: "*.go"
      run: golangci-lint run ./...
    3_govulncheck:
      glob: "*.go"
      run: govulncheck ./...
    4_gotest:
      glob: "*.go"
      run: go test -v ./...
