pre-commit:
  piped: true
  commands:
    1_gomodtidy:
      glob: "*.go"
      run: go mod tidy -diff
    2_golint:
      glob: "*.go"
      run: golangci-lint run ./...
    3_gotest:
      glob: "*.go"
      run: go test -v ./...
