pre-commit:
  piped: true
  commands:
    gomodtidy:
      glob: "*.go"
      run: go mod tidy -diff
    golint:
      glob: "*.go"
      run: golangci-lint run ./...
    gotest:
      glob: "*.go"
      run: go test -v ./...
