# https://opentelemetry.io/docs/collector/configuration/#basics
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:${env:OTELCOL_GRPC_PORT}
      http:
        endpoint: 0.0.0.0:${env:OTELCOL_HTTP_PORT}
processors:
  batch:
exporters:
  debug:
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
extensions:
  health_check:
  pprof:
  zpages:
service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/loki]
