# https://opentelemetry.io/docs/collector/configuration/#basics
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:${env:OTELCOL_GRPC_PORT}
      http:
        endpoint: 0.0.0.0:${env:OTELCOL_HTTP_PORT}
processors:
  batch:
exporters:
  debug:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
