name: golang-ci-on-pull-request

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - '.golangci.yml'
      - '.github/workflows/golang-ci-on-pull-request.yml'

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            exit 1
          fi
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: reviewdog/action-golangci-lint@v2
        with:
          go_version_file: go.mod
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go test -v ./...